# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'pokedek' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for pokedek
  pod 'Alamofire'
  pod 'Kingfisher', '~> 5.0'

end
